name: fpv
services:
  db:
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro

  wp:
    depends_on:
      - db
    build: 
      dockerfile: ./docker/wp.Dockerfile
      context: .
    environment:
      WP_ENV: develop
    volumes:
      - "../:/var/www/html/wp-content/plugins/plugin"
